import type { BuildingAsset, PreventiveMaintenanceTask, Vendor, WorkOrder } from "./types";

/* Timestamps are generated relative to module load so the demo data always
   reads as "live" — an overdue SLA is overdue today, not in 2024. */
const NOW = new Date();

function hoursAgo(hours: number): string {
  return new Date(NOW.getTime() - hours * 3_600_000).toISOString();
}

function hoursFromNow(hours: number): string {
  return new Date(NOW.getTime() + hours * 3_600_000).toISOString();
}

function daysFromNow(days: number, hour = 9, minute = 0): string {
  return new Date(
    NOW.getFullYear(),
    NOW.getMonth(),
    NOW.getDate() + days,
    hour,
    minute
  ).toISOString();
}

export const WORK_ORDERS: WorkOrder[] = [
  {
    id: "wo-2041",
    number: "WO-2041",
    title: "Chiller #2 tripping on high discharge pressure",
    description:
      "Unit trips within 20 minutes of compressor start-up. Head pressure spikes past 410 psi before the safety cutout. Suspect fouled condenser tubes or a failing condenser fan motor. Building automation shows CH-02 fault code 47 repeating.",
    status: "in_progress",
    priority: "critical",
    category: "HVAC",
    location: "Tower A — Mechanical Penthouse",
    floor: "Roof",
    assetTag: "CH-02",
    requestedBy: "BAS alarm — Automation desk",
    assignedVendor: "Apex Mechanical Group",
    assignedTechnician: "M. Okafor (Apex)",
    createdAt: hoursAgo(10),
    scheduledFor: hoursAgo(8),
    completedAt: null,
    slaDueAt: hoursFromNow(2),
    isEmergency: false,
    checklist: [
      { id: "wo-2041-1", label: "LOTO applied and verified", done: true },
      { id: "wo-2041-2", label: "Recovered refrigerant charge for leak check", done: true },
      { id: "wo-2041-3", label: "Brush clean condenser tubes", done: true },
      { id: "wo-2041-4", label: "Rebuild condenser fan motor bearing", done: false },
      { id: "wo-2041-5", label: "Restart, log pressures over 60-min run", done: false },
    ],
    notes: [
      {
        id: "wo-2041-n1",
        author: "Dana Reyes",
        body: "Night engineer confirmed trip at 05:50. LOTO applied before roof access — condenser approach running 14°F above design.",
        createdAt: hoursAgo(9),
        source: "typed",
      },
      {
        id: "wo-2041-n2",
        author: "M. Okafor (Apex)",
        body: "Tubes brushed and flushed. Found scale build-up on two passes; fan motor bearing is noisy and being replaced from van stock.",
        createdAt: hoursAgo(1),
        source: "typed",
      },
    ],
  },
  {
    id: "wo-2042",
    number: "WO-2042",
    title: "Elevator 3 door reopening repeatedly at lobby",
    description:
      "Car 3 in bank B reopens its doors two or three times before closing. Front desk reports it happening most mornings with heavy cart traffic. Possible misaligned door sensor or dirty sill track.",
    status: "assigned",
    priority: "high",
    category: "Elevators",
    location: "Tower A — Lobby, Bank B",
    floor: "1",
    assetTag: "EL-03",
    requestedBy: "Front desk — A. Johnson",
    assignedVendor: "Vertical Transport Services",
    assignedTechnician: "Pending vendor ETA",
    createdAt: hoursAgo(8),
    scheduledFor: hoursFromNow(3),
    completedAt: null,
    slaDueAt: hoursFromNow(9),
    isEmergency: false,
    checklist: [
      { id: "wo-2042-1", label: "Review fault log from controller", done: false },
      { id: "wo-2042-2", label: "Inspect and clean sill track", done: false },
      { id: "wo-2042-3", label: "Realign/replace door detector unit", done: false },
      { id: "wo-2042-4", label: "Run 20 open-close cycles, log results", done: false },
    ],
    notes: [
      {
        id: "wo-2042-n1",
        author: "A. Johnson (Front desk)",
        body: "Happens most with luggage carts — doors bounce open right before closing.",
        createdAt: hoursAgo(7),
        source: "typed",
      },
    ],
  },
  {
    id: "wo-2043",
    number: "WO-2043",
    title: "Domestic hot water booster pump seal weeping",
    description:
      "DHW-P2 mechanical seal is weeping steadily into the containment pan. No loss of pressure yet but the pan float alarm will trip overnight. Seal kit is on the shelf in stores (part #96410871).",
    status: "assigned",
    priority: "high",
    category: "Plumbing",
    location: "Tower B — Pump Room 2",
    floor: "B2",
    assetTag: "DHW-P2",
    requestedBy: "Round inspection — D. Reyes",
    assignedVendor: null,
    assignedTechnician: "D. Reyes (in-house)",
    createdAt: hoursAgo(5),
    scheduledFor: daysFromNow(1, 8),
    completedAt: null,
    slaDueAt: hoursFromNow(19),
    isEmergency: false,
    checklist: [
      { id: "wo-2043-1", label: "Isolate pump, verify LOTO", done: false },
      { id: "wo-2043-2", label: "Replace mechanical seal kit", done: false },
      { id: "wo-2043-3", label: "Bump test and check rotation", done: false },
      { id: "wo-2043-4", label: "Monitor pan for 24h, close out", done: false },
    ],
    notes: [
      {
        id: "wo-2043-n1",
        author: "Dana Reyes",
        body: "Seal kit located in stores. Scheduling for tomorrow AM before the pan float trips the alarm.",
        createdAt: hoursAgo(4),
        source: "typed",
      },
    ],
  },
  {
    id: "wo-2044",
    number: "WO-2044",
    title: "Parking deck section C — six light poles out",
    description:
      "Security patrol flagged a dark stretch on Level 2, section C, between ramps 2 and 3. Six LED heads out; breaker 2A-14 is live so likely failed drivers or photocell bank.",
    status: "new",
    priority: "medium",
    category: "Electrical",
    location: "Parking Garage — Level 2, Section C",
    floor: "P2",
    assetTag: "LT-C12",
    requestedBy: "Security patrol — 3rd shift",
    assignedVendor: null,
    assignedTechnician: null,
    createdAt: hoursAgo(14),
    scheduledFor: daysFromNow(2, 10),
    completedAt: null,
    slaDueAt: daysFromNow(3, 17),
    isEmergency: false,
    checklist: [
      { id: "wo-2044-1", label: "Confirm circuit 2A-14 loading", done: false },
      { id: "wo-2044-2", label: "Replace LED driver heads (6 poles)", done: false },
      { id: "wo-2044-3", label: "Verify photocell bank operation", done: false },
      { id: "wo-2044-4", label: "Update panel schedule as-built", done: false },
    ],
    notes: [],
  },
  {
    id: "wo-2045",
    number: "WO-2045",
    title: "Fire alarm panel trouble — Zone 12 wiring fault",
    description:
      "FACP showing trouble on Zone 12 (Tower A, floor 12 corridor devices). Zone isolated per code; fire watch posted at 30-minute roving intervals pending marshal sign-off.",
    status: "on_hold",
    priority: "critical",
    category: "Fire & Life Safety",
    location: "Tower A — Floor 12 riser closet",
    floor: "12",
    assetTag: "FACP-1",
    requestedBy: "BAS trouble alarm",
    assignedVendor: "Sentinel Fire Protection",
    assignedTechnician: "P. Shah (Sentinel)",
    createdAt: hoursAgo(7),
    scheduledFor: hoursAgo(6),
    completedAt: null,
    slaDueAt: hoursFromNow(5),
    isEmergency: false,
    checklist: [
      { id: "wo-2045-1", label: "Isolate zone per NFPA 72 procedure", done: true },
      { id: "wo-2045-2", label: "Locate wiring fault in riser closet", done: false },
      { id: "wo-2045-3", label: "Repair conductor, restore zone", done: false },
      { id: "wo-2045-4", label: "File inspection/test report with AHJ", done: false },
    ],
    notes: [
      {
        id: "wo-2045-n1",
        author: "P. Shah (Sentinel)",
        body: "On hold pending fire watch sign-off from the marshal's office. Fire watch is roving every 30 minutes.",
        createdAt: hoursAgo(6),
        source: "typed",
      },
    ],
  },
  {
    id: "wo-2046",
    number: "WO-2046",
    title: "Dock leveler 2 will not lock in stored position",
    description:
      "Hydraulic dock leveler at Bay 2 creeps up from stored position and the lock solenoid will not engage. Bay restricted to light vans only until repaired.",
    status: "assigned",
    priority: "medium",
    category: "General",
    location: "Loading Dock — Bay 2",
    floor: "G",
    assetTag: "DL-02",
    requestedBy: "Dock supervisor — R. Ellis",
    assignedVendor: "Dock & Door Pros",
    assignedTechnician: "Pending vendor ETA",
    createdAt: hoursAgo(28),
    scheduledFor: daysFromNow(1, 13),
    completedAt: null,
    slaDueAt: hoursFromNow(11),
    isEmergency: false,
    checklist: [
      { id: "wo-2046-1", label: "Barricade bay, verify pit condition", done: false },
      { id: "wo-2046-2", label: "Inspect lock solenoid and velocity fuse", done: false },
      { id: "wo-2046-3", label: "Repair or replace lock assembly", done: false },
      { id: "wo-2046-4", label: "Cycle test ×10 with rated load", done: false },
    ],
    notes: [],
  },
  {
    id: "wo-2047",
    number: "WO-2047",
    title: "Restroom 4B faucet running continuously",
    description:
      "Cold-side cartridge on the accessible lavatory is not seating; fixture runs constantly. Shut-off valves under the sink are seized, so fixture isolation is needed first.",
    status: "new",
    priority: "low",
    category: "Plumbing",
    location: "Tower B — Restroom 4B",
    floor: "4",
    assetTag: null,
    requestedBy: "Tenant request — Suite 410",
    assignedVendor: null,
    assignedTechnician: null,
    createdAt: hoursAgo(2),
    scheduledFor: daysFromNow(2, 9),
    completedAt: null,
    slaDueAt: daysFromNow(4, 17),
    isEmergency: false,
    checklist: [
      { id: "wo-2047-1", label: "Isolate fixture (replace seized stops)", done: false },
      { id: "wo-2047-2", label: "Rebuild cartridge, replace aerator", done: false },
      { id: "wo-2047-3", label: "Check for leaks under fixture", done: false },
    ],
    notes: [],
  },
  {
    id: "wo-2048",
    number: "WO-2048",
    title: "AHU-3 quarterly filter change and belt inspection",
    description:
      "Scheduled quarterly PM for air handler 3: swap 12 filters (24×24×2 MERV 13), inspect belt tension and pulley alignment, log differential pressure before/after.",
    status: "completed",
    priority: "low",
    category: "HVAC",
    location: "Tower A — Mechanical room 902",
    floor: "9",
    assetTag: "AHU-03",
    requestedBy: "PM schedule PM-118",
    assignedVendor: null,
    assignedTechnician: "M. Webb (in-house)",
    createdAt: hoursAgo(96),
    scheduledFor: hoursAgo(50),
    completedAt: hoursAgo(47),
    slaDueAt: hoursAgo(44),
    isEmergency: false,
    checklist: [
      { id: "wo-2048-1", label: "Log pre-filter ΔP", done: true },
      { id: "wo-2048-2", label: "Replace 12× MERV 13 filters", done: true },
      { id: "wo-2048-3", label: "Inspect belt tension and sheaves", done: true },
      { id: "wo-2048-4", label: "Log post-filter ΔP, reset BAS", done: true },
    ],
    notes: [
      {
        id: "wo-2048-n1",
        author: "M. Webb (in-house)",
        body: "ΔP dropped from 1.4 to 0.6 in. w.g. after swap. Belt and sheaves within spec. Photo set attached in the field log.",
        createdAt: hoursAgo(47),
        source: "typed",
      },
    ],
  },
  {
    id: "wo-2049",
    number: "WO-2049",
    title: "Replace failed exit sign battery packs — floor 2",
    description:
      "Monthly egress walk found two exit signs on floor 2 failing the 90-second battery test. Swapped battery packs from spares and retested.",
    status: "completed",
    priority: "medium",
    category: "Electrical",
    location: "Tower A — Floor 2 corridors",
    floor: "2",
    assetTag: "EX-201",
    requestedBy: "Egress walk — M. Webb",
    assignedVendor: null,
    assignedTechnician: "M. Webb (in-house)",
    createdAt: hoursAgo(30),
    scheduledFor: hoursAgo(26),
    completedAt: hoursAgo(25),
    slaDueAt: hoursAgo(20),
    isEmergency: false,
    checklist: [
      { id: "wo-2049-1", label: "Replace battery pack at EX-201", done: true },
      { id: "wo-2049-2", label: "Replace battery pack at EX-207", done: true },
      { id: "wo-2049-3", label: "Retest 90-second emergency hold", done: true },
    ],
    notes: [],
  },
];

export const PM_TASKS: PreventiveMaintenanceTask[] = [
  {
    id: "pm-101",
    number: "PM-101",
    title: "Cooling tower water treatment check",
    assetTag: "CT-01",
    assetName: "Baltimore cooling tower",
    category: "HVAC",
    frequency: "Weekly",
    nextDue: daysFromNow(1, 6),
    assignedVendor: "Apex Mechanical Group",
    estimatedHours: 1,
    lastCompleted: hoursAgo(168),
  },
  {
    id: "pm-102",
    number: "PM-102",
    title: "Generator monthly load test",
    assetTag: "GEN-1",
    assetName: "Cummins 750 kW standby generator",
    category: "Electrical",
    frequency: "Monthly",
    nextDue: daysFromNow(2, 7),
    assignedVendor: "Metro Electric Co.",
    estimatedHours: 2,
    lastCompleted: hoursAgo(720),
  },
  {
    id: "pm-103",
    number: "PM-103",
    title: "Elevator quarterly safety inspection",
    assetTag: "EL-03",
    assetName: "Otis Gen2 traction elevator",
    category: "Elevators",
    frequency: "Quarterly",
    nextDue: daysFromNow(3, 6),
    assignedVendor: "Vertical Transport Services",
    estimatedHours: 4,
    lastCompleted: hoursAgo(2160),
  },
  {
    id: "pm-104",
    number: "PM-104",
    title: "Chiller condenser tube cleaning",
    assetTag: "CH-02",
    assetName: "Carrier 500-ton centrifugal chiller",
    category: "HVAC",
    frequency: "Quarterly",
    nextDue: daysFromNow(5, 8),
    assignedVendor: "Apex Mechanical Group",
    estimatedHours: 8,
    lastCompleted: hoursAgo(2160),
  },
  {
    id: "pm-105",
    number: "PM-105",
    title: "Fire pump flow test",
    assetTag: "FP-1",
    assetName: "Peerless 750 GPM fire pump",
    category: "Fire & Life Safety",
    frequency: "Monthly",
    nextDue: daysFromNow(8, 7),
    assignedVendor: "Sentinel Fire Protection",
    estimatedHours: 2,
    lastCompleted: hoursAgo(720),
  },
  {
    id: "pm-106",
    number: "PM-106",
    title: "Roof drain and scupper inspection",
    assetTag: "RF-01",
    assetName: "Tower A roof membrane, section N",
    category: "General",
    frequency: "Monthly",
    nextDue: daysFromNow(11, 10),
    assignedVendor: null,
    estimatedHours: 2,
    lastCompleted: hoursAgo(720),
  },
  {
    id: "pm-107",
    number: "PM-107",
    title: "Backflow preventer annual certification",
    assetTag: "BF-01",
    assetName: "2in domestic backflow assembly",
    category: "Plumbing",
    frequency: "Annual",
    nextDue: daysFromNow(15, 9),
    assignedVendor: "ClearFlow Plumbing & Drainage",
    estimatedHours: 3,
    lastCompleted: hoursAgo(8760),
  },
  {
    id: "pm-108",
    number: "PM-108",
    title: "AHU filter change — floors 5–12",
    assetTag: "AHU-03",
    assetName: "Air handling unit 3",
    category: "HVAC",
    frequency: "Quarterly",
    nextDue: daysFromNow(22, 8),
    assignedVendor: null,
    estimatedHours: 4,
    lastCompleted: hoursAgo(47),
  },
];

export const VENDORS: Vendor[] = [
  {
    id: "ven-001",
    name: "Apex Mechanical Group",
    trades: ["HVAC"],
    contactName: "Dana Whitfield — Dispatch",
    phone: "(312) 555-0147",
    email: "dispatch@apexmechanical.example",
    rating: 4.8,
    slaResponseHours: 4,
    preferred: true,
    contractEnd: daysFromNow(205, 0),
  },
  {
    id: "ven-002",
    name: "Metro Electric Co.",
    trades: ["Electrical"],
    contactName: "Luis Ortega",
    phone: "(312) 555-0182",
    email: "service@metroelectric.example",
    rating: 4.6,
    slaResponseHours: 6,
    preferred: true,
    contractEnd: daysFromNow(120, 0),
  },
  {
    id: "ven-003",
    name: "ClearFlow Plumbing & Drainage",
    trades: ["Plumbing"],
    contactName: "Sam Becker",
    phone: "(312) 555-0129",
    email: "24-7@clearflow.example",
    rating: 4.4,
    slaResponseHours: 4,
    preferred: true,
    contractEnd: daysFromNow(300, 0),
  },
  {
    id: "ven-004",
    name: "Vertical Transport Services",
    trades: ["Elevators"],
    contactName: "Grace Kim — Control desk",
    phone: "(312) 555-0163",
    email: "entrapment@verticalts.example",
    rating: 4.9,
    slaResponseHours: 1,
    preferred: true,
    contractEnd: daysFromNow(410, 0),
  },
  {
    id: "ven-005",
    name: "Sentinel Fire Protection",
    trades: ["Fire & Life Safety"],
    contactName: "Tony Marchetti",
    phone: "(312) 555-0111",
    email: "central@sentinelfp.example",
    rating: 4.7,
    slaResponseHours: 2,
    preferred: true,
    contractEnd: daysFromNow(60, 0),
  },
  {
    id: "ven-006",
    name: "Dock & Door Pros",
    trades: ["General"],
    contactName: "Ray Holloway",
    phone: "(312) 555-0158",
    email: "schedule@dockdoorpros.example",
    rating: 4.2,
    slaResponseHours: 24,
    preferred: false,
    contractEnd: daysFromNow(35, 0),
  },
];

export const ASSETS: BuildingAsset[] = [
  {
    id: "ast-001",
    tag: "CH-02",
    name: "Carrier 500-ton centrifugal chiller",
    category: "HVAC",
    location: "Tower A — Mechanical Penthouse",
    floor: "Roof",
    criticality: "critical",
    manufacturer: "Carrier",
    model: "19XR-500",
    installedYear: 2014,
    warrantyEnds: null,
    lastServiceDate: hoursAgo(2),
    openWorkOrderCount: 1,
  },
  {
    id: "ast-002",
    tag: "AHU-03",
    name: "Air handling unit 3",
    category: "HVAC",
    location: "Tower A — Mechanical room 902",
    floor: "9",
    criticality: "high",
    manufacturer: "Trane",
    model: "Performance Climate Changer",
    installedYear: 2014,
    warrantyEnds: null,
    lastServiceDate: hoursAgo(47),
    openWorkOrderCount: 0,
  },
  {
    id: "ast-003",
    tag: "EL-03",
    name: "Traction elevator, bank B car 3",
    category: "Elevators",
    location: "Tower A — Lobby, Bank B",
    floor: "1",
    criticality: "critical",
    manufacturer: "Otis",
    model: "Gen2",
    installedYear: 2014,
    warrantyEnds: daysFromNow(90, 0),
    lastServiceDate: hoursAgo(26),
    openWorkOrderCount: 1,
  },
  {
    id: "ast-004",
    tag: "FACP-1",
    name: "Fire alarm control panel",
    category: "Fire & Life Safety",
    location: "Tower A — Main vestibule",
    floor: "1",
    criticality: "critical",
    manufacturer: "Notifier",
    model: "NFS-320",
    installedYear: 2014,
    warrantyEnds: null,
    lastServiceDate: hoursAgo(7),
    openWorkOrderCount: 1,
  },
  {
    id: "ast-005",
    tag: "DHW-P2",
    name: "Domestic hot water booster pump 2",
    category: "Plumbing",
    location: "Tower B — Pump Room 2",
    floor: "B2",
    criticality: "high",
    manufacturer: "Grundfos",
    model: "CR 15-3",
    installedYear: 2014,
    warrantyEnds: null,
    lastServiceDate: hoursAgo(5),
    openWorkOrderCount: 1,
  },
  {
    id: "ast-006",
    tag: "GEN-1",
    name: "750 kW standby diesel generator",
    category: "Electrical",
    location: "Tower B — Generator yard",
    floor: "G",
    criticality: "critical",
    manufacturer: "Cummins",
    model: "C750 D5",
    installedYear: 2014,
    warrantyEnds: null,
    lastServiceDate: daysFromNow(-30, 7),
    openWorkOrderCount: 0,
  },
  {
    id: "ast-007",
    tag: "DL-02",
    name: "Hydraulic dock leveler, Bay 2",
    category: "General",
    location: "Loading Dock — Bay 2",
    floor: "G",
    criticality: "medium",
    manufacturer: "Rite-Hite",
    model: "RHM-4000",
    installedYear: 2014,
    warrantyEnds: null,
    lastServiceDate: hoursAgo(28),
    openWorkOrderCount: 1,
  },
  {
    id: "ast-008",
    tag: "CT-01",
    name: "Cooling tower, north cell",
    category: "HVAC",
    location: "Tower A — Roof, north bay",
    floor: "Roof",
    criticality: "high",
    manufacturer: "Baltimore Aircoil",
    model: "VXT-35",
    installedYear: 2014,
    warrantyEnds: null,
    lastServiceDate: hoursAgo(168),
    openWorkOrderCount: 0,
  },
];

export const CURRENT_USER = {
  name: "Dana Reyes",
  role: "Building Engineer II",
  shift: "Day (07:00–15:30)" as const,
};
