import type { BuildingAsset, PmTask, Technician, TimelineEntry, Vendor, WorkOrder } from "./types";

/* Timestamps are generated relative to module load so the demo data always
   reads as "live" — an overdue SLA is overdue today, not in 2024. */
const NOW = new Date();

function hoursAgo(h: number): string {
  return new Date(NOW.getTime() - h * 3_600_000).toISOString();
}
function hoursFromNow(h: number): string {
  return new Date(NOW.getTime() + h * 3_600_000).toISOString();
}
function daysFromNow(d: number, hour = 9, minute = 0): string {
  return new Date(NOW.getFullYear(), NOW.getMonth(), NOW.getDate() + d, hour, minute).toISOString();
}
function daysAgo(d: number, hour = 9): string {
  return daysFromNow(-d, hour);
}

let tSeq = 0;
function tl(p: Omit<TimelineEntry, "id">): TimelineEntry {
  return { id: `t-${tSeq++}`, ...p };
}

/* ------------------------------- technicians ------------------------------ */

export const TECHNICIANS: Technician[] = [
  {
    id: "tech-reyes",
    name: "Dana Reyes",
    role: "Building Engineer II",
    shift: "Day (07:00–15:30)",
    phone: "(312) 555-0104",
    email: "d.reyes@meridianfac.example",
    specialties: ["HVAC", "General"],
    hue: 25,
  },
  {
    id: "tech-webb",
    name: "Marcus Webb",
    role: "HVAC Mechanic",
    shift: "Day (07:00–15:30)",
    phone: "(312) 555-0119",
    email: "m.webb@meridianfac.example",
    specialties: ["HVAC"],
    hue: 200,
  },
  {
    id: "tech-okafor",
    name: "Chidi Okafor",
    role: "Electrician",
    shift: "Swing (15:00–23:30)",
    phone: "(312) 555-0142",
    email: "c.okafor@meridianfac.example",
    specialties: ["Electrical", "Security"],
    hue: 45,
  },
  {
    id: "tech-shah",
    name: "Priya Shah",
    role: "Plumber",
    shift: "Day (07:00–15:30)",
    phone: "(312) 555-0167",
    email: "p.shah@meridianfac.example",
    specialties: ["Plumbing"],
    hue: 210,
  },
  {
    id: "tech-ellis",
    name: "Robin Ellis",
    role: "General Maintenance Tech",
    shift: "Night (23:00–07:30)",
    phone: "(312) 555-0188",
    email: "r.ellis@meridianfac.example",
    specialties: ["General", "Cleaning", "Structural"],
    hue: 150,
  },
];

/* --------------------------------- assets --------------------------------- */

export const ASSETS: BuildingAsset[] = [
  {
    id: "ast-ch01",
    tag: "CH-01",
    name: "Centrifugal chiller #1",
    category: "HVAC",
    location: {
      building: "Central Plant",
      floor: "Basement (B1)",
      zone: "Zone 2 — Core",
      room: "CP-01",
    },
    manufacturer: "Carrier",
    model: "19XR 500-ton",
    installedAt: "2014-05-12",
    warrantyEnds: null,
    lastServiceAt: hoursAgo(52),
    criticality: "critical",
  },
  {
    id: "ast-ch02",
    tag: "CH-02",
    name: "Centrifugal chiller #2",
    category: "HVAC",
    location: {
      building: "Central Plant",
      floor: "Basement (B1)",
      zone: "Zone 2 — Core",
      room: "CP-01",
    },
    manufacturer: "Carrier",
    model: "19XR 500-ton",
    installedAt: "2014-05-12",
    warrantyEnds: null,
    lastServiceAt: hoursAgo(2),
    criticality: "critical",
  },
  {
    id: "ast-ahu03",
    tag: "AHU-03",
    name: "Air handling unit 3",
    category: "HVAC",
    location: { building: "Building A", floor: "9", zone: "Zone 2 — Core", room: "902" },
    manufacturer: "Trane",
    model: "Performance Climate Changer",
    installedAt: "2014-06-01",
    warrantyEnds: null,
    lastServiceAt: hoursAgo(47),
    criticality: "high",
  },
  {
    id: "ast-ahu05",
    tag: "AHU-05",
    name: "Air handling unit 5",
    category: "HVAC",
    location: { building: "Building B", floor: "Roof", zone: "Zone 3 — South", room: "RT-5" },
    manufacturer: "Trane",
    model: "Performance Climate Changer",
    installedAt: "2014-06-01",
    warrantyEnds: null,
    lastServiceAt: daysAgo(41),
    criticality: "high",
  },
  {
    id: "ast-ct01",
    tag: "CT-01",
    name: "Cooling tower, north cell",
    category: "HVAC",
    location: { building: "Central Plant", floor: "Roof", zone: "Zone 1 — North", room: "CT-BAY" },
    manufacturer: "Baltimore Aircoil",
    model: "VXT-35",
    installedAt: "2014-05-20",
    warrantyEnds: null,
    lastServiceAt: hoursAgo(168),
    criticality: "high",
  },
  {
    id: "ast-vav312",
    tag: "VAV-312",
    name: "VAV box, suite 312",
    category: "HVAC",
    location: { building: "Building A", floor: "3", zone: "Zone 3 — South", room: "312" },
    manufacturer: "Titus",
    model: "T2ZS-12",
    installedAt: "2019-08-15",
    warrantyEnds: daysFromNow(30),
    lastServiceAt: daysAgo(120),
    criticality: "low",
  },
  {
    id: "ast-dhwp2",
    tag: "DHW-P2",
    name: "Domestic hot water booster pump 2",
    category: "Plumbing",
    location: {
      building: "Building B",
      floor: "Basement (B1)",
      zone: "Zone 2 — Core",
      room: "PUMP-2",
    },
    manufacturer: "Grundfos",
    model: "CR 15-3",
    installedAt: "2014-07-01",
    warrantyEnds: null,
    lastServiceAt: hoursAgo(5),
    criticality: "high",
  },
  {
    id: "ast-ris4",
    tag: "RIS-4",
    name: "Domestic water riser 4",
    category: "Plumbing",
    location: {
      building: "Building A",
      floor: "Basement (B1)",
      zone: "Zone 1 — North",
      room: "RISER-4",
    },
    manufacturer: "—",
    model: "4in copper riser",
    installedAt: "2014-03-10",
    warrantyEnds: null,
    lastServiceAt: daysAgo(200),
    criticality: "high",
  },
  {
    id: "ast-lav410",
    tag: "LAV-410",
    name: "Accessible lavatory, suite 410",
    category: "Plumbing",
    location: { building: "Building B", floor: "4", zone: "Zone 2 — Core", room: "410" },
    manufacturer: "Kohler",
    model: "Kingston",
    installedAt: "2021-02-20",
    warrantyEnds: daysFromNow(220),
    lastServiceAt: daysAgo(90),
    criticality: "low",
  },
  {
    id: "ast-el03",
    tag: "EL-03",
    name: "Traction elevator, bank B car 3",
    category: "Other",
    location: { building: "Building A", floor: "1", zone: "Zone 2 — Core", room: "LOBBY-B" },
    manufacturer: "Otis",
    model: "Gen2",
    installedAt: "2014-04-18",
    warrantyEnds: daysFromNow(90),
    lastServiceAt: hoursAgo(26),
    criticality: "critical",
  },
  {
    id: "ast-el07",
    tag: "EL-07",
    name: "Traction elevator, bank C car 2",
    category: "Other",
    location: { building: "Building B", floor: "1", zone: "Zone 1 — North", room: "LOBBY-C" },
    manufacturer: "Kone",
    model: "MonoSpace 500",
    installedAt: "2016-11-05",
    warrantyEnds: null,
    lastServiceAt: daysAgo(14),
    criticality: "high",
  },
  {
    id: "ast-gen1",
    tag: "GEN-1",
    name: "750 kW standby diesel generator",
    category: "Electrical",
    location: { building: "Building B", floor: "1", zone: "Zone 3 — South", room: "GEN-YARD" },
    manufacturer: "Cummins",
    model: "C750 D5",
    installedAt: "2014-09-30",
    warrantyEnds: null,
    lastServiceAt: daysAgo(30, 7),
    criticality: "critical",
  },
  {
    id: "ast-ats1",
    tag: "ATS-1",
    name: "Automatic transfer switch 1",
    category: "Electrical",
    location: {
      building: "Building B",
      floor: "Basement (B1)",
      zone: "Zone 2 — Core",
      room: "ELEC-1",
    },
    manufacturer: "ASC0",
    model: "TS-940",
    installedAt: "2014-09-30",
    warrantyEnds: null,
    lastServiceAt: daysAgo(60),
    criticality: "critical",
  },
  {
    id: "ast-lt2c",
    tag: "LT-2C",
    name: "Parking lighting circuit 2C",
    category: "Electrical",
    location: {
      building: "Building A",
      floor: "Basement (B1)",
      zone: "Zone 3 — South",
      room: "P2-C",
    },
    manufacturer: "—",
    model: "LED pole heads ×24",
    installedAt: "2018-06-11",
    warrantyEnds: null,
    lastServiceAt: daysAgo(75),
    criticality: "medium",
  },
  {
    id: "ast-facp1",
    tag: "FACP-1",
    name: "Fire alarm control panel",
    category: "Security",
    location: { building: "Building A", floor: "1", zone: "Zone 2 — Core", room: "VEST-1" },
    manufacturer: "Notifier",
    model: "NFS-320",
    installedAt: "2014-04-02",
    warrantyEnds: null,
    lastServiceAt: hoursAgo(7),
    criticality: "critical",
  },
];

/* --------------------------------- vendors -------------------------------- */

export const VENDORS: Vendor[] = [
  {
    id: "ven-apex",
    name: "Apex Mechanical Group",
    specialty: "HVAC",
    contactName: "Dana Whitfield — Dispatch",
    phone: "(312) 555-0147",
    email: "dispatch@apexmech.example",
    rating: 4.8,
    responseTargetHours: 4,
    avgResponseHours: 2.6,
    slaCompliancePct: 96,
    qualityScore: 94,
    completedJobs90d: 38,
    contractStatus: "Active",
    contractEnd: daysFromNow(205),
  },
  {
    id: "ven-metro",
    name: "Metro Electric Co.",
    specialty: "Electrical",
    contactName: "Luis Ortega",
    phone: "(312) 555-0182",
    email: "service@metroelec.example",
    rating: 4.6,
    responseTargetHours: 6,
    avgResponseHours: 4.1,
    slaCompliancePct: 93,
    qualityScore: 91,
    completedJobs90d: 24,
    contractStatus: "Active",
    contractEnd: daysFromNow(120),
  },
  {
    id: "ven-clearflow",
    name: "ClearFlow Plumbing & Drainage",
    specialty: "Plumbing",
    contactName: "Sam Becker",
    phone: "(312) 555-0129",
    email: "24-7@clearflow.example",
    rating: 4.4,
    responseTargetHours: 4,
    avgResponseHours: 3.5,
    slaCompliancePct: 90,
    qualityScore: 88,
    completedJobs90d: 31,
    contractStatus: "Active",
    contractEnd: daysFromNow(300),
  },
  {
    id: "ven-vertical",
    name: "Vertical Transport Services",
    specialty: "Elevator",
    contactName: "Grace Kim — Control desk",
    phone: "(312) 555-0163",
    email: "entrapment@verticalts.example",
    rating: 4.9,
    responseTargetHours: 1,
    avgResponseHours: 0.8,
    slaCompliancePct: 99,
    qualityScore: 97,
    completedJobs90d: 19,
    contractStatus: "Active",
    contractEnd: daysFromNow(410),
  },
  {
    id: "ven-sentinel",
    name: "Sentinel Fire Protection",
    specialty: "Fire Safety",
    contactName: "Tony Marchetti",
    phone: "(312) 555-0111",
    email: "central@sentinelfp.example",
    rating: 4.7,
    responseTargetHours: 2,
    avgResponseHours: 1.9,
    slaCompliancePct: 97,
    qualityScore: 95,
    completedJobs90d: 15,
    contractStatus: "Renewal due",
    contractEnd: daysFromNow(60),
  },
  {
    id: "ver-green",
    id2: undefined as never,
    name: "GreenScape Grounds",
    specialty: "Landscaping",
    contactName: "Hector Ramos",
    phone: "(312) 555-0136",
    email: "crew@greenscape.example",
    rating: 4.1,
    responseTargetHours: 24,
    avgResponseHours: 19.5,
    slaCompliancePct: 84,
    qualityScore: 80,
    completedJobs90d: 12,
    contractStatus: "Expiring",
    contractEnd: daysFromNow(35),
  } as unknown as Vendor,
];

/* -------------------------------- work orders ------------------------------ */

function parts(p: Array<[string, number, number, "on_hand" | "ordered" | "backordered"]>) {
  return p.map(([name, qty, unitCost, status], i) => ({
    id: `part-${partSeq()}-${i}`,
    name,
    qty,
    unitCost,
    status,
  }));
}
let pSeq = 0;
function partSeq() {
  return ++pSeq;
}

export const WORK_ORDERS: WorkOrder[] = [
  {
    id: "wo-2101",
    number: "WO-2101",
    title: "Chiller #2 tripping on high discharge pressure",
    description:
      "CH-02 trips within 20 minutes of compressor start-up. Head pressure spikes past 410 psi before the safety cutout. BAS shows fault code 47 repeating. Suspect fouled condenser tubes or failing condenser fan motor; night engineer confirmed trip at 05:50.",
    status: "in_progress",
    priority: "critical",
    category: "HVAC",
    location: {
      building: "Central Plant",
      floor: "Basement (B1)",
      zone: "Zone 2 — Core",
      room: "CP-01",
    },
    assetId: "ast-ch02",
    reportedBy: "BAS alarm — Automation desk",
    reportedAt: hoursAgo(10),
    dueAt: hoursFromNow(2),
    assigneeId: "tech-webb",
    vendorId: "ven-apex",
    isEmergency: true,
    parts: parts([
      ["Condenser tube brush kit", 2, 45, "on_hand"],
      ["Fan motor bearing 6206-2RS", 4, 18, "on_hand"],
      ["Refrigerant R-134a (lb)", 40, 11, "ordered"],
    ]),
    timeline: [
      tl({ at: hoursAgo(10), type: "status", actor: "BAS alarm", to: "New Request" }),
      tl({
        at: hoursAgo(9),
        type: "assignment",
        actor: "Dana Reyes",
        message: "Dispatched Apex Mechanical — emergency rate",
      }),
      tl({
        at: hoursAgo(9),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
      tl({
        at: hoursAgo(8),
        type: "comment",
        actor: "Marcus Webb",
        message: "LOTO applied, recovered charge for tube inspection.",
      }),
      tl({
        at: hoursAgo(8),
        type: "status",
        actor: "Marcus Webb",
        from: "Assigned",
        to: "In Progress",
      }),
      tl({
        at: hoursAgo(1),
        type: "photo",
        actor: "Marcus Webb",
        message: "Scale build-up on condenser passes 2–3",
        photoCount: 3,
      }),
    ],
    photos: [
      { id: "ph-1", caption: "Condenser head removed — scale on passes" },
      { id: "ph-2", caption: "BAS fault history screenshot" },
      { id: "ph-3", caption: "Fan motor bearing wear" },
    ],
    completedAt: null,
  },
  {
    id: "wo-2102",
    number: "WO-2102",
    title: "Elevator 3 door reopening repeatedly at lobby",
    description:
      "Car 3 in bank B reopens doors two or three times before closing. Front desk reports it worst during morning cart traffic. Possible misaligned door detector or debris in sill track.",
    status: "assigned",
    priority: "high",
    category: "Other",
    location: { building: "Building A", floor: "1", zone: "Zone 2 — Core", room: "LOBBY-B" },
    assetId: "ast-el03",
    reportedBy: "Front desk — A. Johnson",
    reportedAt: hoursAgo(8),
    dueAt: hoursFromNow(9),
    assigneeId: null,
    vendorId: "ven-vertical",
    isEmergency: false,
    parts: parts([["Door detector unit (aftermarket)", 1, 320, "ordered"]]),
    timeline: [
      tl({ at: hoursAgo(8), type: "status", actor: "A. Johnson", to: "New Request" }),
      tl({
        at: hoursAgo(7),
        type: "comment",
        actor: "A. Johnson",
        message: "Happens most with luggage carts — doors bounce open right before closing.",
      }),
      tl({
        at: hoursAgo(7),
        type: "assignment",
        actor: "Dana Reyes",
        message: "Dispatched Vertical Transport; ETA pending control desk.",
      }),
      tl({
        at: hoursAgo(7),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
    ],
    photos: [{ id: "ph-4", caption: "Sill track debris (lobby cam still)" }],
    completedAt: null,
  },
  {
    id: "wo-2103",
    number: "WO-2103",
    title: "DHW booster pump 2 seal weeping into containment pan",
    description:
      "DHW-P2 mechanical seal weeping steadily; pan float alarm will trip overnight if unchecked. Seal kit on the shelf in stores (part #96410871). Isolation valves confirmed operable.",
    status: "assigned",
    priority: "high",
    category: "Plumbing",
    location: {
      building: "Building B",
      floor: "Basement (B1)",
      zone: "Zone 2 — Core",
      room: "PUMP-2",
    },
    assetId: "ast-dhwp2",
    reportedBy: "Round inspection — D. Reyes",
    reportedAt: hoursAgo(5),
    dueAt: hoursFromNow(19),
    assigneeId: "tech-shah",
    vendorId: null,
    isEmergency: false,
    parts: parts([
      ["Mechanical seal kit #96410871", 1, 148, "on_hand"],
      ["Gasket set", 1, 22, "on_hand"],
    ]),
    timeline: [
      tl({ at: hoursAgo(5), type: "status", actor: "D. Reyes", to: "New Request" }),
      tl({
        at: hoursAgo(4),
        type: "assignment",
        actor: "Dana Reyes",
        message: "Assigned to P. Shah — day shift, first thing tomorrow.",
      }),
      tl({
        at: hoursAgo(4),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
    ],
    photos: [],
    completedAt: null,
  },
  {
    id: "wo-2104",
    number: "WO-2104",
    title: "Parking level P2 section C — six light poles out",
    description:
      "Security patrol flagged a dark stretch on P2 section C between ramps 2 and 3. Six LED heads out; breaker 2A-14 live so likely failed drivers or photocell bank.",
    status: "awaiting_parts",
    priority: "medium",
    category: "Electrical",
    location: {
      building: "Building A",
      floor: "Basement (B1)",
      zone: "Zone 3 — South",
      room: "P2-C",
    },
    assetId: "ast-lt2c",
    reportedBy: "Security patrol — 3rd shift",
    reportedAt: hoursAgo(14),
    dueAt: daysFromNow(3, 17),
    assigneeId: "tech-okafor",
    vendorId: null,
    isEmergency: false,
    parts: parts([
      ["LED driver 60W", 6, 38, "backordered"],
      ["Photocell", 2, 15, "on_hand"],
    ]),
    timeline: [
      tl({ at: hoursAgo(14), type: "status", actor: "Security patrol", to: "New Request" }),
      tl({
        at: hoursAgo(12),
        type: "assignment",
        actor: "Dana Reyes",
        message: "Assigned to C. Okafor (swing).",
      }),
      tl({
        at: hoursAgo(12),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
      tl({
        at: hoursAgo(6),
        type: "status",
        actor: "C. Okafor",
        from: "In Progress",
        to: "Awaiting Parts",
      }),
      tl({
        at: hoursAgo(6),
        type: "comment",
        actor: "C. Okafor",
        message: "Drivers backordered at supply house — ETA Thursday. Photocells in stock.",
      }),
    ],
    photos: [{ id: "ph-5", caption: "Dark section C, pole 12–17" }],
    completedAt: null,
  },
  {
    id: "wo-2105",
    number: "WO-2105",
    title: "Fire alarm panel trouble — Zone 12 wiring fault",
    description:
      "FACP showing trouble on Zone 12 (floor 12 corridor devices). Zone isolated per code; fire watch posted at 30-minute roving intervals pending marshal sign-off.",
    status: "in_progress",
    priority: "critical",
    category: "Security",
    location: { building: "Building A", floor: "12", zone: "Zone 2 — Core", room: "RISER-12" },
    assetId: "ast-facp1",
    reportedBy: "BAS trouble alarm",
    reportedAt: hoursAgo(7),
    dueAt: hoursFromNow(5),
    assigneeId: null,
    vendorId: "ven-sentinel",
    isEmergency: true,
    parts: parts([["FPLR 12/2 cable (ft)", 300, 1.4, "on_hand"]]),
    timeline: [
      tl({ at: hoursAgo(7), type: "status", actor: "BAS alarm", to: "New Request" }),
      tl({
        at: hoursAgo(6),
        type: "assignment",
        actor: "Dana Reyes",
        message: "Sentinel Fire dispatched — life safety emergency.",
      }),
      tl({
        at: hoursAgo(6),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
      tl({
        at: hoursAgo(5),
        type: "status",
        actor: "P. Shah (Sentinel)",
        from: "Assigned",
        to: "In Progress",
      }),
      tl({
        at: hoursAgo(5),
        type: "comment",
        actor: "P. Shah (Sentinel)",
        message: "On hold pending fire watch sign-off from marshal's office.",
      }),
    ],
    photos: [{ id: "ph-6", caption: "Zone 12 riser closet conductor damage" }],
    completedAt: null,
  },
  {
    id: "wo-2106",
    number: "WO-2106",
    title: "VAV-312 stuck at minimum airflow — suite 312 warm calls",
    description:
      "Tenant in suite 312 reports space stuck at 78°F all week. VAV damper not modulating; actuator clicks but shaft appears slipped. DDC shows 0% feedback regardless of command.",
    status: "reported",
    priority: "medium",
    category: "HVAC",
    location: { building: "Building A", floor: "3", zone: "Zone 3 — South", room: "312" },
    assetId: "ast-vav312",
    reportedBy: "Tenant request — Suite 312",
    reportedAt: hoursAgo(3),
    dueAt: daysFromNow(3),
    assigneeId: null,
    vendorId: null,
    isEmergency: false,
    parts: parts([["VAV actuator 24V", 1, 96, "on_hand"]]),
    timeline: [tl({ at: hoursAgo(3), type: "status", actor: "Suite 312", to: "New Request" })],
    photos: [],
    completedAt: null,
  },
  {
    id: "wo-2107",
    number: "WO-2107",
    title: "Restroom 4B lavatory running continuously",
    description:
      "Cold-side cartridge on the accessible lavatory is not seating; fixture runs constantly. Shut-off stops under the sink are seized, so fixture isolation needed first.",
    status: "reported",
    priority: "low",
    category: "Plumbing",
    location: { building: "Building B", floor: "4", zone: "Zone 2 — Core", room: "410" },
    assetId: "ast-lav410",
    reportedBy: "Tenant request — Suite 410",
    reportedAt: hoursAgo(2),
    dueAt: daysFromNow(7),
    assigneeId: null,
    vendorId: null,
    isEmergency: false,
    parts: parts([["Lavatory cartridge", 1, 34, "on_hand"]]),
    timeline: [tl({ at: hoursAgo(2), type: "status", actor: "Suite 410", to: "New Request" })],
    photos: [],
    completedAt: null,
  },
  {
    id: "wo-2108",
    number: "WO-2108",
    title: "Dock leveler 2 will not lock in stored position",
    description:
      "Hydraulic dock leveler at Bay 2 creeps up from stored position; lock solenoid will not engage. Bay restricted to light vans only until repaired.",
    status: "in_progress",
    priority: "medium",
    category: "General",
    location: { building: "Building B", floor: "1", zone: "Zone 3 — South", room: "DOCK-2" },
    assetId: null,
    reportedBy: "Dock supervisor — R. Ellis",
    reportedAt: hoursAgo(28),
    dueAt: hoursFromNow(11),
    assigneeId: "tech-ellis",
    vendorId: null,
    isEmergency: false,
    parts: parts([["Lock solenoid kit", 1, 78, "ordered"]]),
    timeline: [
      tl({ at: hoursAgo(28), type: "status", actor: "R. Ellis", to: "New Request" }),
      tl({
        at: hoursAgo(26),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
      tl({
        at: hoursAgo(24),
        type: "status",
        actor: "R. Ellis",
        from: "Assigned",
        to: "In Progress",
      }),
      tl({
        at: hoursAgo(20),
        type: "comment",
        actor: "R. Ellis",
        message: "Solenoid coil reads open. Kit ordered, barricade stays up.",
      }),
    ],
    photos: [],
    completedAt: null,
  },
  {
    id: "wo-2109",
    number: "WO-2109",
    title: "Corridor ceiling tile stain — suspected A/C condensate",
    description:
      "Water stain spreading on corridor ceiling tiles outside suite 505. AHU-05 condensate drain suspected; ceiling grid compromised, two tiles sagging.",
    status: "assigned",
    priority: "low",
    category: "Structural",
    location: {
      building: "Building B",
      floor: "5" as string,
      zone: "Zone 1 — North",
      room: "COR-505",
    },
    assetId: null,
    reportedBy: "Engineering walk — M. Webb",
    reportedAt: hoursAgo(30),
    dueAt: daysFromNow(6),
    assigneeId: "tech-ellis",
    vendorId: null,
    isEmergency: false,
    parts: parts([["2×4 ceiling tiles", 8, 9, "on_hand"]]),
    timeline: [
      tl({ at: hoursAgo(30), type: "status", actor: "M. Webb", to: "New Request" }),
      tl({
        at: hoursAgo(29),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
    ],
    photos: [{ id: "ph-7", caption: "Stain extent outside suite 505" }],
    completedAt: null,
  },
  {
    id: "wo-2110",
    number: "WO-2110",
    title: "AHU-3 quarterly filter change and belt inspection",
    description:
      "Scheduled quarterly PM turned work order: swap 12 filters (24×24×2 MERV 13), inspect belt tension and pulley alignment, log differential pressure before/after.",
    status: "verified",
    priority: "low",
    category: "HVAC",
    location: { building: "Building A", floor: "9", zone: "Zone 2 — Core", room: "902" },
    assetId: "ast-ahu03",
    reportedBy: "PM schedule PM-108",
    reportedAt: hoursAgo(96),
    dueAt: hoursAgo(44),
    assigneeId: "tech-webb",
    vendorId: null,
    isEmergency: false,
    parts: parts([["MERV 13 filter 24×24×2", 12, 21, "on_hand"]]),
    timeline: [
      tl({ at: hoursAgo(96), type: "status", actor: "PM-108", to: "New Request" }),
      tl({
        at: hoursAgo(50),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
      tl({
        at: hoursAgo(48),
        type: "status",
        actor: "M. Webb",
        from: "Assigned",
        to: "In Progress",
      }),
      tl({
        at: hoursAgo(47),
        type: "status",
        actor: "M. Webb",
        from: "In Progress",
        to: "Completed",
      }),
      tl({
        at: hoursAgo(40),
        type: "comment",
        actor: "Dana Reyes",
        message: "ΔP logs verified against BAS trend — closing out.",
      }),
      tl({
        at: hoursAgo(40),
        type: "status",
        actor: "Dana Reyes",
        from: "Completed",
        to: "Verified",
      }),
    ],
    photos: [{ id: "ph-8", caption: "Filter bank after swap" }],
    completedAt: hoursAgo(47),
  },
  {
    id: "wo-2111",
    number: "WO-2111",
    title: "Replace failed exit sign battery packs — floor 2",
    description:
      "Monthly egress walk found two exit signs on floor 2 failing the 90-second battery test. Battery packs swapped from spares and retested.",
    status: "completed",
    priority: "medium",
    category: "Electrical",
    location: { building: "Building A", floor: "3", zone: "Zone 1 — North", room: "COR-2" },
    assetId: null,
    reportedBy: "Egress walk — M. Webb",
    reportedAt: hoursAgo(30),
    dueAt: daysFromNow(1),
    assigneeId: "tech-okafor",
    vendorId: null,
    isEmergency: false,
    parts: parts([["Exit sign battery pack", 2, 26, "on_hand"]]),
    timeline: [
      tl({ at: hoursAgo(30), type: "status", actor: "M. Webb", to: "New Request" }),
      tl({
        at: hoursAgo(26),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
      tl({
        at: hoursAgo(25),
        type: "status",
        actor: "C. Okafor",
        from: "Assigned",
        to: "In Progress",
      }),
      tl({
        at: hoursAgo(25),
        type: "status",
        actor: "C. Okafor",
        from: "In Progress",
        to: "Completed",
      }),
    ],
    photos: [],
    completedAt: hoursAgo(25),
  },
  {
    id: "wo-2112",
    number: "WO-2112",
    title: "Emergency generator fuel polish quote — annual PM finding",
    description:
      "Annual load test passed but fuel sample shows microbial growth at the tank bottom. Fuel polishing vendor quote requested per policy before summer peak season.",
    status: "awaiting_parts",
    priority: "low",
    category: "Electrical",
    location: { building: "Building B", floor: "1", zone: "Zone 3 — South", room: "GEN-YARD" },
    assetId: "ast-gen1",
    reportedBy: "PM-102 annual test findings",
    reportedAt: daysAgo(6, 10),
    dueAt: daysFromNow(9),
    assigneeId: null,
    vendorId: "ven-metro",
    isEmergency: false,
    parts: parts([["Fuel polishing service (quote pending)", 1, 2400, "backordered"]]),
    timeline: [
      tl({ at: daysAgo(6, 10), type: "status", actor: "PM-102", to: "New Request" }),
      tl({
        at: daysAgo(5),
        type: "assignment",
        actor: "Dana Reyes",
        message: "Metro Electric coordinating fuel sub.",
      }),
      tl({
        at: daysAgo(5),
        type: "status",
        actor: "Dana Reyes",
        from: "New Request",
        to: "Assigned",
      }),
      tl({
        at: daysAgo(4),
        type: "status",
        actor: "L. Ortega (Metro)",
        from: "In Progress",
        to: "Awaiting Parts",
      }),
      tl({
        at: daysAgo(4),
        type: "comment",
        actor: "L. Ortega (Metro)",
        message: "Polishing sub booked, awaiting slot confirmation.",
      }),
    ],
    photos: [{ id: "ph-9", caption: "Fuel sample jar — bottom sediment" }],
    completedAt: null,
  },
];

/* ------------------------------ PM schedule ------------------------------- */

export const PM_TASKS: PmTask[] = [
  {
    id: "pm-101",
    number: "PM-101",
    title: "Cooling tower water treatment check",
    taskType: "Water treatment",
    frequency: "Weekly",
    assetId: "ast-ct01",
    assignedTechId: null,
    vendorId: "ven-apex",
    nextDue: daysFromNow(1, 6),
    estHours: 1,
    history: [
      {
        completedAt: daysAgo(7, 6),
        completedBy: "Apex Mechanical",
        notes: "Biocide levels nominal; TDS 1,850 ppm.",
      },
      {
        completedAt: daysAgo(14, 6),
        completedBy: "Apex Mechanical",
        notes: "Bleed valve cleaned.",
      },
      { completedAt: daysAgo(21, 6), completedBy: "Apex Mechanical", notes: "Routine check." },
    ],
  },
  {
    id: "pm-102",
    number: "PM-102",
    title: "Generator monthly load test",
    taskType: "Load test",
    frequency: "Monthly",
    assetId: "ast-gen1",
    assignedTechId: "tech-okafor",
    vendorId: "ven-metro",
    nextDue: daysFromNow(2, 7),
    estHours: 2,
    history: [
      {
        completedAt: daysAgo(30, 7),
        completedBy: "Metro Electric",
        notes: "30-min load bank test passed; fuel sample pulled (see WO-2112).",
      },
      {
        completedAt: daysAgo(61, 7),
        completedBy: "Metro Electric",
        notes: "Passed; battery float 27.2V.",
      },
    ],
  },
  {
    id: "pm-103",
    number: "PM-103",
    title: "Elevator quarterly safety inspection",
    taskType: "Safety inspection",
    frequency: "Quarterly",
    assetId: "ast-el03",
    assignedTechId: null,
    vendorId: "ven-vertical",
    nextDue: daysFromNow(-2, 6),
    estHours: 4,
    history: [
      {
        completedAt: daysAgo(92, 6),
        completedBy: "Vertical Transport",
        notes: "Cat 1 test passed; door detector aging — monitor.",
      },
      {
        completedAt: daysAgo(183, 6),
        completedBy: "Vertical Transport",
        notes: "Annual cat 5 witnessed by AHJ.",
      },
    ],
  },
  {
    id: "pm-104",
    number: "PM-104",
    title: "Chiller condenser tube cleaning",
    taskType: "Tube cleaning",
    frequency: "Quarterly",
    assetId: "ast-ch02",
    assignedTechId: null,
    vendorId: "ven-apex",
    nextDue: daysFromNow(-5, 8),
    estHours: 8,
    history: [
      {
        completedAt: daysAgo(96, 8),
        completedBy: "Apex Mechanical",
        notes: "Brush cleaned; approach temp 2.1°F above design.",
      },
      {
        completedAt: daysAgo(187, 8),
        completedBy: "Apex Mechanical",
        notes: "Eddy current scan clean.",
      },
    ],
  },
  {
    id: "pm-105",
    number: "PM-105",
    title: "Fire pump churn test",
    taskType: "Flow test",
    frequency: "Weekly",
    assetId: "ast-facp1",
    assignedTechId: "tech-okafor",
    vendorId: null,
    nextDue: daysFromNow(4, 7),
    estHours: 1,
    history: [
      {
        completedAt: daysAgo(3, 7),
        completedBy: "C. Okafor",
        notes: "Churn test 12 psig; jockey pump cycling normally.",
      },
      { completedAt: daysAgo(10, 7), completedBy: "C. Okafor", notes: "Passed." },
    ],
  },
  {
    id: "pm-106",
    number: "PM-106",
    title: "AHU-3 filter change (quarterly)",
    taskType: "Filter change",
    frequency: "Quarterly",
    assetId: "ast-ahu03",
    assignedTechId: "tech-webb",
    vendorId: null,
    nextDue: daysFromNow(20, 8),
    estHours: 4,
    history: [
      {
        completedAt: daysAgo(2, 9),
        completedBy: "M. Webb",
        notes: "ΔP 1.4 → 0.6 in. w.g. after swap. See WO-2110.",
      },
    ],
  },
  {
    id: "pm-107",
    number: "PM-107",
    title: "Backflow preventer annual certification",
    taskType: "Certification",
    frequency: "Annual",
    assetId: "ast-ris4",
    assignedTechId: null,
    vendorId: "ven-clearflow",
    nextDue: daysFromNow(15, 9),
    estHours: 3,
    history: [
      {
        completedAt: daysAgo(350, 9),
        completedBy: "ClearFlow Plumbing",
        notes: "Certified; report filed with water authority.",
      },
    ],
  },
  {
    id: "pm-108",
    number: "PM-108",
    title: "Rooftop unit belt & bearing inspection",
    taskType: "Belt/bearing inspection",
    frequency: "Monthly",
    assetId: "ast-ahu05",
    assignedTechId: "tech-webb",
    vendorId: null,
    nextDue: daysFromNow(-1, 10),
    estHours: 2,
    history: [
      {
        completedAt: daysAgo(31, 10),
        completedBy: "M. Webb",
        notes: "Belt tension within spec; bearing grease applied.",
      },
      { completedAt: daysAgo(62, 10), completedBy: "M. Webb", notes: "Passed." },
    ],
  },
];

/* Status-bar identity for the signed-in engineer. */
export const CURRENT_USER = {
  name: "Dana Reyes",
  role: "Building Engineer II",
  shift: "Day (07:00–15:30)" as const,
};
